version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
clone_depth: 5
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)
install:
- ps: >-
    if($($env:APPVEYOR))

    {

    $firstCommit = $(git log --pretty=format:'%H' -n -1).Length;

    $firstCommitHash = $(git log --pretty=format:'%H' -n -1)[$firstCommit-1];

    Write-Host "First Commit Hash:" $firstCommitHash;

    $firstCommitDate = (git show -s --format=%ci $firstCommitHash);

    Write-Host "First Commit Date:" $firstCommitDate;

    [datetime]$FCDateTime = $firstCommitDate;

    #Write-Host $FCDateTime

    $FCyear = $FCDateTime.ToString("y.").TrimEnd('.');

    #Write-Host $FCyear

    $timeZone0 = [TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Turkey Standard Time");

    $timeZone = $timeZone0;

    Write-Host "Current System Time:" $timeZone;

    [datetime]$DateTime = $timeZone;

    $year = $DateTime.ToString("y.").TrimEnd('.');

    $month = $DateTime.ToString("M.").TrimEnd('.');

    $day = $DateTime.ToString("d.").TrimEnd('.');

    $hourMinute = $DateTime.ToString(".HHmm").TrimStart('.').TrimStart('0');

    $buildYear = (($year - $FCyear) + 1);

    #$buildTime = $DateTime.ToString("M.d.hmm");

    $newBuildNumber = "$buildYear.$month.$day.$hourMinute";

    Write-Host "New Nuget Package Version:" $newBuildNumber

    Update-AppveyorBuild -Version $newBuildNumber;

    }

    else

    {
        Write-Host "AppVeyor was not detected";
    }
build_script:
- ps: >-
    if($($env:APPVEYOR))
    {

    $SVersion = $($env:APPVEYOR_BUILD_VERSION);
    Write-Host "$($env:APPVEYOR_PROJECT_NAME) Version:$SVersion";

    dotnet clean -c Release;
    nuget restore;
    dotnet msbuild /p:Configuration=Release /p:Version=$newBuildNumber;

    $riotgamesapi = "$($env:APPVEYOR_PROJECT_NAME)";
    Write-Host  $riotgamesapi;

    $riotgamesapiAspNet = "$riotgamesapi.AspNet";
    Write-Host  $riotgamesapiAspNet;

    $riotgamesapiAspNetCore = "$riotgamesapi.AspNetCore";
    Write-Host  $riotgamesapiAspNetCore;

    nuget pack "$riotgamesapi.nuspec" -version $newBuildNumber;
    nuget pack "$riotgamesapiAspNet.nuspec" -version $newBuildNumber;
    nuget pack "$riotgamesapiAspNetCore.nuspec" -version $newBuildNumber;

    Push-AppveyorArtifact "$($env:APPVEYOR_BUILD_FOLDER)\$riotgamesapi.$SVersion.nupkg" -FileName "$riotgamesapi.$SVersion.nupkg" -DeploymentName "$riotgamesapi";
    Push-AppveyorArtifact "$($env:APPVEYOR_BUILD_FOLDER)\$riotgamesapiAspNet.$SVersion.nupkg" -FileName "$riotgamesapiAspNet.$SVersion.nupkg" -DeploymentName "$riotgamesapiAspNet";
    Push-AppveyorArtifact "$($env:APPVEYOR_BUILD_FOLDER)\$riotgamesapiAspNetCore.$SVersion.nupkg" -FileName "$riotgamesapiAspNetCore.$SVersion.nupkg" -DeploymentName "$riotgamesapiAspNetCore";

    }
    else
    {
    Write-Host "AppVeyor was not detected";
    }
test: off
hosts:
  api.nuget.org: 93.184.221.200
skip_commits:
  files:
    - '**/*.md'
